# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:

jobs:
  build:
    runs-on: self-hosted
    
  steps:
    - name: testrun
      run: PowerShell -Command "dir env:"
