# This is a basic workflow to help you get started with Actions
name: CI

on: 
  push:

jobs:
  testenv:
    runs-on: self-hosted
    steps:
      - name: testrun
        run: powershell "dir env:"
      - name: compile
        run: "dotnet tool restore"
